export enum ChapaUrls {
  INITIALIZE = '/transaction/initialize',
  MOBILE_INITIALIZE = '/transaction/mobile-initialize',
  VERIFY = '/transaction/verify',
  BANK = '/banks',
  SUBACCOUNT = '/subaccount',
  TRANSACTION = '/transactions',
  TRANSACTION_LOG = '/transaction/events',
  TRANSFER = '/transfers',
  BULK_TRANSFER = '/bulk-transfers',
  VERIFY_TRANSFER = '/transfers/verify',
  DIRECT_CHARGE = '/charges',
  AUTHORIZE_DIRECT_CHARGE = '/validate',
  REFUND = '/refund',
}
